'use client';
import { useState } from 'react';
import { Intake, scoreDeal } from '../lib/risk';
import RoleBadge from '../components/RoleBadge';
const initial: Intake = { make:'Toyota', model:'Premio', year:2018, mileage:78000, value:32000000, income:2800000, incomeType:'Business', mobileMoney:'Strong', crb:'Clear', location:'Kampala' };
const money = (n:number) => `UGX ${Math.round(n).toLocaleString('en-UG')}`;
function Icon({children}:{children:React.ReactNode}){return <span className="icon">{children}</span>}
export default function Home(){
 const [data,setData]=useState<Intake>(initial); const [result,setResult]=useState(scoreDeal(initial)); const [consent,setConsent]=useState(true);
 const update=(key:keyof Intake,value:string)=>{const next={...data,[key]: ['year','mileage','value','income'].includes(key)?Number(value):value} as Intake; setData(next);setResult(scoreDeal(next));};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="logo">K</div><div><b>keylo</b><small>UGANDA</small></div></div><div className="org"><span className="orgmark">KA</span><div><strong>Kampala Auto Hub</strong><small>Dealer workspace</small></div><span className="chevron">⌄</span></div><nav><a className="active"><Icon>⌂</Icon>Overview</a><a><Icon>＋</Icon>New assessment</a><a><Icon>▣</Icon>Applications <em>12</em></a><a><Icon>◷</Icon>Decision history</a><div className="navlabel">WORKSPACE</div><a><Icon>♙</Icon>Team members</a><a><Icon>⚙</Icon>Settings</a></nav><div className="help"><div className="helpicon">?</div><div><b>Need a hand?</b><small>Read the underwriting guide</small></div></div><div className="profile"><div className="avatar">JM</div><div><b>Joseph M.</b><small>Administrator</small></div><span>•••</span></div></aside>
  <section className="content"><header><div className="crumb">Overview <span>/</span> New assessment</div><div className="header-actions"><RoleBadge/><button className="iconbtn">⌕</button><button className="iconbtn">♧</button><div className="avatar">JM</div></div></header>
   <div className="page-title"><div><div className="eyebrow">NEW ASSESSMENT <span className="live">● LIVE</span></div><h1>Vehicle access assessment</h1><p>Build a transparent, explainable offer in under 3 minutes.</p></div><div className="save">● &nbsp;All changes saved</div></div>
   <div className="steps"><div className="step done"><b>01</b><span>Deal details</span></div><div className="line filled"/><div className="step current"><b>02</b><span>Risk assessment</span></div><div className="line"/><div className="step"><b>03</b><span>Decision</span></div></div>
   <div className="grid"><div className="form-card card"><div className="card-head"><div><h2>Deal details</h2><p>Tell us about the vehicle and subscriber.</p></div><span className="required">* Required fields</span></div><div className="section-label">VEHICLE INFORMATION</div><div className="fields"><Field label="Make" value={data.make} onChange={v=>update('make',v)} /><Field label="Model" value={data.model} onChange={v=>update('model',v)} /><Field label="Year" value={data.year} type="number" onChange={v=>update('year',v)} /><Field label="Mileage (km)" value={data.mileage} type="number" onChange={v=>update('mileage',v)} /><Field label="Estimated value (UGX)" value={data.value} type="number" onChange={v=>update('value',v)} wide /></div><div className="section-label subscriber">SUBSCRIBER PROFILE</div><div className="fields"><Field label="Monthly income (UGX)" value={data.income} type="number" onChange={v=>update('income',v)} /><Select label="Income type" value={data.incomeType} options={['Business','Formal','Casual']} onChange={v=>update('incomeType',v)} /><Select label="Mobile-money activity" value={data.mobileMoney} options={['Strong','Regular','Limited']} onChange={v=>update('mobileMoney',v)} /><Select label="CRB status" value={data.crb} options={['Clear','Unknown','Flagged']} onChange={v=>update('crb',v)} /><Field label="Primary location" value={data.location} onChange={v=>update('location',v)} /><Field label="Phone number" value="+256 7•• ••• 482" onChange={()=>{}} /></div><div className="consent"><input id="consent" type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><label htmlFor="consent">I have the subscriber's consent to check CRB, mobile-money and loan signals.</label><a href="#privacy">View disclosure</a></div><div className="form-foot"><span>🔒 Data is encrypted and access is logged</span><button className="secondary">Save draft</button><button className="primary" disabled={!consent}>Continue <span>→</span></button></div></div>
    <aside className="result-card card"><div className="result-head"><div><div className="eyebrow">PREVIEW</div><h2>Risk snapshot</h2></div><span className="spark">⌁</span></div><div className="score-wrap"><div className={`score-ring tier-${result.tier}`}><strong>{result.combined}</strong><span>/ 100</span></div><div><div className={`tier tier-${result.tier}`}>TIER {result.tier}</div><b className="score-title">{result.tier==='A'?'Strong candidate':result.tier==='B'?'Good with conditions':result.tier==='C'?'Review carefully':'Do not proceed'}</b><p>Blended risk score</p></div></div><div className="metric"><span>Asset score <b>ⓘ</b></span><strong>{result.asset}<small>/100</small></strong><div className="bar"><i style={{width:`${result.asset}%`}}/></div></div><div className="metric"><span>Subscriber score <b>ⓘ</b></span><strong>{result.subscriber}<small>/100</small></strong><div className="bar"><i style={{width:`${result.subscriber}%`}}/></div></div><div className="signals"><div><span className="pulse"/> SIGNAL COVERAGE</div><b>2 of 3 sources connected</b><small>gnuGrid Mobile Credit Score · self-declared income</small></div><div className="factors"><div className="section-label">TOP DRIVERS</div>{result.factors.map((f,i)=><div className="factor" key={f}><span className={`factor-icon f${i}`}>{i===0?'↗':i===1?'◔':'✓'}</span>{f}</div>)}</div><div className="offer"><div><span>Recommended access fee</span><b>{money(result.monthly)} <small>/ month</small></b></div><div className="offer-row"><span>Security deposit <b>{money(result.deposit)}</b></span><span>Suggested term <b>{result.term} months</b></span></div><div className="offer-row"><span>Est. margin <b className="green">{result.margin}%</b></span><span>Location <b>{data.location}</b></span></div></div><div className="engine"><span className="pulse"/> Rules engine v1 <span>Updated just now</span></div></aside></div>
   <footer><span>KeyLo Underwriting OS <b>•</b> Kampala, Uganda</span><span>Privacy &amp; audit logs <b>•</b> v0.1.0</span></footer>
  </section></main>
}
function Field({label,value,onChange,type='text',wide=false}:{label:string,value:string|number,onChange:(v:string)=>void,type?:string,wide?:boolean}){return <label className={wide?'wide':''}>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
