-- KeyLo Uganda MVP schema (PostgreSQL)
create extension if not exists "uuid-ossp";
create type risk_tier as enum ('A','B','C','DECLINE');
create type organization_type as enum ('DEALER','SACCO','MFI','BANK','FLEET');
create table organizations (id uuid primary key default uuid_generate_v4(), name text not null, type organization_type not null, country_code char(2) default 'UG', risk_config jsonb not null default '{}', created_at timestamptz not null default now());
create table users (id uuid primary key default uuid_generate_v4(), organization_id uuid not null references organizations(id), email text not null, full_name text not null, role text not null, created_at timestamptz not null default now());
create table vehicles (id uuid primary key default uuid_generate_v4(), organization_id uuid not null references organizations(id), make text not null, model text not null, year smallint not null, mileage_km integer, vin text, chassis_number text, estimated_value_ugx bigint not null, created_at timestamptz not null default now());
create table subscribers (id uuid primary key default uuid_generate_v4(), organization_id uuid not null references organizations(id), nin_hash text, phone_hash text not null, occupation text, income_type text, estimated_monthly_income_ugx bigint, location text, consent_at timestamptz, created_at timestamptz not null default now());
create table deals (id uuid primary key default uuid_generate_v4(), organization_id uuid not null references organizations(id), vehicle_id uuid not null references vehicles(id), subscriber_id uuid not null references subscribers(id), status text not null default 'DRAFT', term_months smallint, deposit_ugx bigint, monthly_subscription_ugx bigint, created_by uuid references users(id), created_at timestamptz not null default now());
create table data_consents (id uuid primary key default uuid_generate_v4(), organization_id uuid not null references organizations(id), deal_id uuid references deals(id), subscriber_id uuid not null references subscribers(id), purpose text not null, provider text not null, consent_text text not null, method text not null check(method in ('OTP','DIGITAL_SIGNATURE','PHYSICAL_FORM')), initiated_by uuid references users(id), ip_address inet, captured_by uuid references users(id), otp_verified_at timestamptz, captured_at timestamptz not null default now(), revoked_at timestamptz);
create table external_risk_signals (id uuid primary key default uuid_generate_v4(), deal_id uuid not null references deals(id), provider text not null, signal_type text not null, provider_reference text, normalized_value jsonb not null, consent_id uuid references data_consents(id), retrieved_at timestamptz not null default now(), expires_at timestamptz, raw_payload_encrypted bytea);
create table payment_events (id uuid primary key default uuid_generate_v4(), organization_id uuid not null references organizations(id), deal_id uuid references deals(id), provider text not null, external_reference text not null, msisdn_hash text not null, amount_ugx bigint, status text not null, payload jsonb not null default '{}', received_at timestamptz not null default now(), unique(provider,external_reference));
-- Normalized, consented source records. Keep these separate from immutable decision snapshots.
create table credit_scores (id uuid primary key default uuid_generate_v4(), subscriber_id uuid not null references subscribers(id), source text not null, score numeric check(score between 0 and 100), score_band text, probability_of_default numeric check(probability_of_default between 0 and 1), provider_reference text, consent_id uuid references data_consents(id), raw_response_encrypted bytea, fetched_at timestamptz not null default now(), expires_at timestamptz);
create table mobile_money_signals (id uuid primary key default uuid_generate_v4(), subscriber_id uuid not null references subscribers(id), provider text not null check(provider in ('MTN','AIRTEL','AGGREGATOR')), avg_monthly_inflow_ugx bigint, consistency_score numeric check(consistency_score between 0 and 100), wallet_turnover_ugx bigint, airtime_regularity_score numeric check(airtime_regularity_score between 0 and 100), sim_tenure_months integer, outstanding_loans_count integer, repayment_success_rate numeric check(repayment_success_rate between 0 and 1), consent_id uuid references data_consents(id), last_updated timestamptz not null default now(), expires_at timestamptz);
create table payments (id uuid primary key default uuid_generate_v4(), deal_id uuid not null references deals(id), provider text not null check(provider in ('MTN','AIRTEL')), external_reference text not null, amount_ugx bigint not null, status text not null check(status in ('PENDING','SUCCESSFUL','FAILED')), provider_transaction_id text, created_at timestamptz not null default now(), unique(provider, external_reference));
create table risk_scores (id uuid primary key default uuid_generate_v4(), deal_id uuid not null references deals(id), engine_version text not null, asset_score smallint not null check(asset_score between 0 and 100), subscriber_score smallint not null check(subscriber_score between 0 and 100), combined_score smallint not null check(combined_score between 0 and 100), tier risk_tier not null, factors jsonb not null, signals jsonb not null, calculated_at timestamptz not null default now());
create table decisions (id uuid primary key default uuid_generate_v4(), deal_id uuid not null references deals(id), risk_score_id uuid not null references risk_scores(id), outcome text not null, conditions jsonb not null default '[]', approved_by uuid references users(id), decided_at timestamptz, notes text);
create table audit_log (id bigserial primary key, organization_id uuid not null references organizations(id), actor_id uuid references users(id), entity_type text not null, entity_id uuid, action text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index deals_org_status on deals(organization_id,status); create index risk_scores_deal on risk_scores(deal_id,calculated_at desc); create index audit_org_time on audit_log(organization_id,created_at desc);
-- Compatibility note: data_consents is the richer canonical consent record; payment_events is the webhook inbox.
-- payments is the normalized payment ledger used by deal views. audit_log is the append-only audit source.
-- Never store raw NIN or phone; retain only salted hashes and explicit consent timestamps.
